version: "2.1"

services:
  zoo1:
    image: zookeeper:3.5
    container_name: zoo
    restart: always
    hostname: zoo1
    ports:
       - "2181:2181"
  kafka:
    image: pandorasystems/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 139.18.19.93
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181

  trellis:
    image: pandorasystems/trellis:0.1.0
    container_name: trellis
    ports:
      - "8080:8080"

